Repository MbrllaHacks/Website, pull requests merged in 2022-07, with the labels that each got.

#34 Set up CI with Azure Pipelines
  azure-pipelines.yml
Labels: enhancement

#35 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: bug, enhancement

#36 Update azure-pipelines.yml for Azure Pipelines
  azure-pipelines.yml
Labels: enhancement

#42 Create nodejsCI.yml
  .github/workflows/nodejsCI.yml
Labels: enhancement

#49 change CD
  .github/workflows/NodeCD.yml
  .github/workflows/nodejsCI.yml
  azure-pipelines.yml
Labels: CICD

#44 Added Build Status
  README.md
Labels: enhancement

#39 Added the Teams Section
  package-lock.json
  src/Assets/shitty_vector_1.svg
  src/Assets/shitty_vector_2.png
  src/components/Teams/Teams.js
  src/components/Teams/teams.module.css
Labels: preview, WIP

#15 Footer
  src/App.js
  src/Assets/logo_white.svg
  src/components/Footer/footer.css
  src/components/Footer/footer.js
Labels: enhancement

#69 Footer
  src/App.js
  src/Assets/logo_white.svg
  src/components/Footer/footer.css
  src/components/Footer/footer.js
Labels: enhancement

#74 Removed all warnings (issue : #70)
  package-lock.json
  package.json
  src/components/About/about.js
  src/components/Contact/contact.js
  src/components/Faq/faq.js
  src/components/Faq/questions.js
  src/components/Footer/footer.js
  src/components/Home/home.js
  src/components/Navbar/navbar.js
  src/components/Sponsors/sponsors.js
Labels: bug

#81 Completed faq
  src/components/Faq/faq.css
  src/components/Faq/faq.js
  src/components/Faq/questions.css
  src/components/Faq/questions.js
Labels: enhancement

#88 Update FAQ and Loading page
  src/components/Faq/faq.js
  src/components/Faq/questions.js
  src/loading.js
  src/style.css
Labels: enhancement
